name: Build/Test & Publish

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-dockerbuild:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        run: |
          docker buildx build --platform linux/arm/v7,linux/arm64,linux/amd64 -t tdtgit/mysql-backup-s3 .
          docker run --rm -it tdtgit/mysql-backup-s3 aws --version

  publish-dockerhub:
    if: github.ref == 'refs/heads/main'
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u tdtgit -p $DOCKER_PASSWORD
          docker buildx build --push --platform linux/arm/v7,linux/arm64,linux/amd64 -t tdtgit/mysql-backup-s3 .